/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2024-12-26 18:44:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Trust Wave | Your Road to Safety and Savings</title>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"assets/style.css\">\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/72fb3712df.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/owl.carousel.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        html, body {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            overflow-x: hidden;\r\n");
      out.write("            background: linear-gradient(to bottom, #ccc, #333);\r\n");
      out.write("            font-family: 'Roboto', sans-serif;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hero-section {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            background: url('img/ook.jpg') no-repeat center center/cover;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hero-section::before {\r\n");
      out.write("            content: \"\";\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            background: rgba(0, 0, 0, 0.3);\r\n");
      out.write("            z-index: 1;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hero-section .blur-box {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            background: rgba(0, 0, 0, 0.6);\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("            z-index: 2;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hero-section h1 {\r\n");
      out.write("            font-size: 4rem;\r\n");
      out.write("            color: rgb(126, 214, 171);;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .hero-section p {\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            color: rgba(255, 255, 255, 0.9);\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("              align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-container a {\r\n");
      out.write("            padding: 15px 30px;\r\n");
      out.write("            font-size: 1.2rem;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            color: #1e432e;;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            background-color: rgb(126, 214, 171);;\r\n");
      out.write("            transition: background-color 0.3s;\r\n");
      out.write("              align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write(".btn-container a:hover {\r\n");
      out.write("  background-color: #754f61;   \r\n");
      out.write("       }\r\n");
      out.write("\r\n");
      out.write("        .additional-section {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            background: #afaeae;\r\n");
      out.write("            padding: 50px;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .additional-section .content {\r\n");
      out.write("            max-width: 600px;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .additional-section ul {\r\n");
      out.write("            padding-left: 20px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .additional-section h2 {\r\n");
      out.write("         color: #333;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .subsections {\r\n");
      out.write("            background: #fff;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            padding: 50px 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .subsection-item {\r\n");
      out.write("            margin: 20px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .subsection-item h3 {\r\n");
      out.write("            color: #285e39;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        footer {\r\n");
      out.write("            background: #222;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Include Header JSP -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "inc/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"hero-section\">\r\n");
      out.write("        <div class=\"blur-box\">\r\n");
      out.write("            <h1>Welcome to Trust Wave</h1>\r\n");
      out.write("            <p>Your Trusted Partner for Secure and Smart Banking</p>\r\n");
      out.write("           <div class=\"btn-container\" style=\"text-align: center;\">\r\n");
      out.write("    <a href=\"login.jsp\" style=\"margin: 10px 0px 10px 250px; display: inline-block;\">Login</a>\r\n");
      out.write("    <a href=\"signup.jsp\" style=\"margin: 10px 10px; display: inline-block;\">Sign Up</a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("            <p class=\"hero-quote\">\"Secure your future, one step at a time.\"</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"additional-section\">\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("            <h2>Why Choose Us?</h2>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><strong>Mobile Banking Features</strong>: Deposit checks, get real-time updates, and manage your finances on the go.</li>\r\n");
      out.write("            <li><strong>Convenient Bill Payments</strong>: Pay bills easily, set up automatic payments, and manage your financial obligations.</li>\r\n");
      out.write("            <li><strong>Budgeting & Financial Tools</strong>: Track spending, set goals, and manage finances with personalized insights.</li>\r\n");
      out.write("            <li><strong>24/7 Customer Support</strong>: Quick, responsive support for any questions or concerns at any time.</li>\r\n");
      out.write("            <li><strong>Competitive Rates</strong>: Get better rates on loans, savings, and credit products.</li>\r\n");
      out.write("            <li><strong>Paperless Transactions</strong>: Eco-friendly and efficient way to manage finances without paperwork.</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"subsections\">\r\n");
      out.write("    <div class=\"dash_container\">\r\n");
      out.write("        <div class=\"dash_box\">\r\n");
      out.write("            <i class=\"fas fa-cogs\"></i> <!-- Optional icon for feature highlight -->\r\n");
      out.write("            <h3>Feature Highlight</h3>\r\n");
      out.write("            <p>Discover our advanced banking features, including AI-driven insights, secure transactions, and personalized dashboards for efficient management of your finances.</p>\r\n");
      out.write("            <a href=\"#\" class=\"btn\">Learn More</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"dash_box\">\r\n");
      out.write("            <i class=\"fas fa-gift\"></i> <!-- Optional icon for exclusive promotions -->\r\n");
      out.write("            <h3>Exclusive Promotions</h3>\r\n");
      out.write("            <p>Enjoy exclusive cashback offers and attractive rewards on your Trust Wave card with every transaction. Experience banking benefits like never before!</p>\r\n");
      out.write("            <a href=\"#\" class=\"btn\">Claim Offer</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"dash_box\">\r\n");
      out.write("            <i class=\"fas fa-globe\"></i> <!-- Optional icon for global reach -->\r\n");
      out.write("            <h3>Global Reach</h3>\r\n");
      out.write("            <p>Bank seamlessly across the globe with our state-of-the-art international banking network, ensuring hassle-free experiences wherever you travel.</p>\r\n");
      out.write("            <a href=\"#\" class=\"btn\">Explore More</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"dash_box\">\r\n");
      out.write("            <i class=\"fas fa-headset\"></i> <!-- Optional icon for 24/7 support -->\r\n");
      out.write("            <h3>24/7 Support</h3>\r\n");
      out.write("            <p>Our dedicated support team is here to assist you around the clock, ensuring your banking experience remains smooth and worry-free at all times.</p>\r\n");
      out.write("            <a href=\"#\" class=\"btn\">Contact Support</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Include Footer JSP -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "inc/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
