/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2024-12-26 16:25:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.bill;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import config.dbconnect;
import javax.servlet.http.HttpSession;

public final class favbill_002dpayee_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
    _jspx_imports_classes.add("config.dbconnect");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!-- Import the dbconnect class -->\r\n");
      out.write(" <!-- Import HttpSession -->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Favorite Bill Payee | EasyBank: Banking at Your Fingertips\r\n");
      out.write("    </title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../assets/style.css\">\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/72fb3712df.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

    if (session.getAttribute("name") == null) {
        response.sendRedirect("../login.jsp");
        return;
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Include Header JSP -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"flex\">\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/acc-dash.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"flex-col content-wrapper m-10\">\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"bredcrumb\">\r\n");
      out.write("            <li><a href=\"../home/home.jsp\">Home</a></li>\r\n");
      out.write("            <li><i class=\"fa-solid fa-chevron-right\"></i></li>\r\n");
      out.write("            <li><a href=\"fund-transfer.php\">Bill Payment Services</a></li>\r\n");
      out.write("            <li><i class=\"fa-solid fa-chevron-right\"></i></li>\r\n");
      out.write("            <li><a href=\"one-timebill.php\">One Time Bill Payment</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"cardG\">\r\n");
      out.write("                <h2 class=\"text-center\">Favorite Bill Payee</h2>\r\n");
      out.write("\r\n");
 
// Retrieve the success message from session
String successMessage = (String) session.getAttribute("success_message");
if (successMessage != null) {

      out.write("\r\n");
      out.write("    <div class=\"alert fade-in\" id=\"successMessage\">\r\n");
      out.write("        ");
      out.print( successMessage );
      out.write("\r\n");
      out.write("        <button class=\"btn-close\" onclick=\"this.parentElement.style.display='none';\">&times;</button>\r\n");
      out.write("    </div>\r\n");

    // Remove the message after displaying it
    session.removeAttribute("success_message");
}

      out.write("\r\n");
      out.write("            <form class=\"content-wrapper form\">\r\n");
      out.write("    <div class=\"form-item\">\r\n");
      out.write("        <label for=\"payeeName\">Payee Name</label>\r\n");
      out.write("        <input type=\"text\" id=\"payeeName\" name=\"payeeName\" placeholder=\"Enter Payee Name\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-item\">\r\n");
      out.write("        <label for=\"payeeAccountNo\">Account Number</label>\r\n");
      out.write("        <input type=\"text\" id=\"payeeAccountNo\" name=\"payeeAccountNo\" placeholder=\"Enter Account Number\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-item\">\r\n");
      out.write("        <label for=\"contactNumber\">Contact Number</label>\r\n");
      out.write("        <input type=\"text\" id=\"contactNumber\" name=\"contactNumber\" placeholder=\"Enter Contact Number\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-item\">\r\n");
      out.write("        <label for=\"branch\">Branch</label>\r\n");
      out.write("        <input type=\"text\" id=\"branch\" name=\"branch\" placeholder=\"Enter Branch\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-item\">\r\n");
      out.write("        <label for=\"serviceProvider\">Service Provider</label>\r\n");
      out.write("        <select id=\"serviceProvider\" name=\"serviceProvider\">\r\n");
      out.write("            <option value=\"electricity\">Electricity</option>\r\n");
      out.write("            <option value=\"water\">Water</option>\r\n");
      out.write("            <option value=\"internet\">Internet</option>\r\n");
      out.write("            <option value=\"telecom\">Telecom</option>\r\n");
      out.write("        </select>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form-item\">\r\n");
      out.write("        <label for=\"billNumber\">Bill Number</label>\r\n");
      out.write("        <input type=\"text\" id=\"billNumber\" name=\"billNumber\" placeholder=\"Enter Bill Number\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <button type=\"submit\" class=\"btn btn-primary\">NEXT</button>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("                <!-- Summary Section -->\r\n");
      out.write("                <h3 class=\"m-10\">Payee Summary</h3>\r\n");
      out.write("               <table>\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>Payee Description</th>\r\n");
      out.write("                                <th>Billing Number</th>\r\n");
      out.write("                                <th>Payee Category</th>\r\n");
      out.write("                                <th>Service Provider</th>\r\n");
      out.write("                             \r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            ");
 
                            String NIC = (String) session.getAttribute("NIC");
                            String sql = "SELECT PayeeID, PayeeCategory, BillAccountNo, ServiceProvider, Description FROM billpayees WHERE NIC = ?";
                            try (Connection conn = dbconnect.connect();
                                 PreparedStatement stmt = conn.prepareStatement(sql)) {
                                 
                                stmt.setString(1, NIC);
                                ResultSet rs = stmt.executeQuery();

                                while (rs.next()) {
                                    String payeeCategory = rs.getString("PayeeCategory");
                                    String billAccountNo = rs.getString("BillAccountNo");
                                    String serviceProvider = rs.getString("ServiceProvider");
                                    String description = rs.getString("Description");
                                    String PayeeID = rs.getString("PayeeID");
                            
      out.write("\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>");
      out.print( description );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( billAccountNo );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( payeeCategory );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( serviceProvider );
      out.write("</td>\r\n");
      out.write("                                    \r\n");
      out.write("                                </tr>\r\n");
      out.write("                            ");
 
                                }
                            } catch (SQLException e) {
                                e.printStackTrace();
                            } 
                            
      out.write("\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("\r\n");
      out.write("                <!-- OTP Section -->\r\n");
      out.write("                <h3 class=\"m-10\">Request OTP</h3>\r\n");
      out.write("                <div class=\"flex\" style=\"text-align: center;\">\r\n");
      out.write("                 <input type=\"text\" id=\"billNumber\" name=\"billNumber\" placeholder=\"Enter OTP Number\" > <br>\r\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary\" style=\"margin: 10px 0px 10px 250px; display: inline-block;\">Verify OTP</button>\r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Include Footer JSP -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
