/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2024-12-26 16:00:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.account;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import config.dbconnect;
import javax.servlet.http.HttpSession;

public final class account_002dsummary_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
    _jspx_imports_classes.add("config.dbconnect");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!-- Import the dbconnect class -->\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>General Services | EasyBank</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../assets/style.css\">\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/72fb3712df.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
 
    if (session.getAttribute("name") == null) {
        response.sendRedirect("../login.jsp");
        return;
    }

      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Include Header JSP -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"flex\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/acc-dash.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"flex-col content-wrapper\">\r\n");
      out.write("            <ul class=\"bredcrumb\">\r\n");
      out.write("                <li><a href=\"../home/home.jsp\">Home</a></li>\r\n");
      out.write("                <li><i class=\"fa-solid fa-chevron-right\"></i></li>\r\n");
      out.write("                <li>General Services</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"cardG flex-col\">\r\n");
      out.write("                    <h2 class=\"text-center\">Our Services</h2>\r\n");
      out.write("                    <p class=\"text-center\">Explore the wide range of online banking services offered by EasyBank.</p>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Services Section -->\r\n");
      out.write("                    <div class=\"service-cards\">\r\n");
      out.write("                        <div class=\"service-card\">\r\n");
      out.write("                            <i class=\"fa-solid fa-wallet fa-3x\"></i>\r\n");
      out.write("                            <h3>Account Management</h3>\r\n");
      out.write("                            <p>Manage your bank account, view your balance, and make account-related changes.</p>\r\n");
      out.write("                            <a href=\"../account/account-summary.jsp\" class=\"btn btn-primary\">View Account</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"service-card\">\r\n");
      out.write("                            <i class=\"fa-solid fa-exchange-alt fa-3x\"></i>\r\n");
      out.write("                            <h3>Fund Transfer</h3>\r\n");
      out.write("                            <p>Transfer funds to other accounts or pay your favorite payees easily and securely.</p>\r\n");
      out.write("                            <a href=\"../transaction/index.jsp\" class=\"btn btn-primary\">Transfer Funds</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"service-card\">\r\n");
      out.write("                            <i class=\"fa-solid fa-bill-wave fa-3x\"></i>\r\n");
      out.write("                            <h3>Bill Payments</h3>\r\n");
      out.write("                            <p>Pay utility bills, credit card bills, and other payments directly from your account.</p>\r\n");
      out.write("                            <a href=\"../payments/bill-payments.jsp\" class=\"btn btn-primary\">Pay Bills</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"service-card\">\r\n");
      out.write("                            <i class=\"fa-solid fa-user-circle fa-3x\"></i>\r\n");
      out.write("                            <h3>Profile Settings</h3>\r\n");
      out.write("                            <p>Update your profile, change your password, and manage your contact details.</p>\r\n");
      out.write("                            <a href=\"../user/profile-settings.jsp\" class=\"btn btn-primary\">Edit Profile</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"service-card\">\r\n");
      out.write("                            <i class=\"fa-solid fa-chart-line fa-3x\"></i>\r\n");
      out.write("                            <h3>Transaction History</h3>\r\n");
      out.write("                            <p>View detailed records of all your transactions and track your spending.</p>\r\n");
      out.write("                            <a href=\"../transaction/transaction-history.jsp\" class=\"btn btn-primary\">View Transactions</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"service-card\">\r\n");
      out.write("                            <i class=\"fa-solid fa-shield-alt fa-3x\"></i>\r\n");
      out.write("                            <h3>Security</h3>\r\n");
      out.write("                            <p>Ensure the security of your account with advanced protection features.</p>\r\n");
      out.write("                            <a href=\"../security/security-settings.jsp\" class=\"btn btn-primary\">Security Settings</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Add the CSS for service cards -->\r\n");
      out.write("<style>\r\n");
      out.write("        /* Service Cards Layout */\r\n");
      out.write("        .service-cards {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            gap: 20px;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .service-card {\r\n");
      out.write("            background-color: #f9f9f9;\r\n");
      out.write("            border: 1px solid #ddd;\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            width: 300px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            transition: transform 0.3s ease;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            flex-direction: column;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .service-card:hover {\r\n");
      out.write("            transform: translateY(-5px); /* Slight lift effect on hover */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .service-card i {\r\n");
      out.write("            color: #01aebc;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .service-card h3 {\r\n");
      out.write("            font-size: 1.5rem;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .service-card p {\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            color: #555;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .service-card .btn {\r\n");
      out.write("            padding: 10px 20px;\r\n");
      out.write("            background-color: #01aebc;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            transition: background-color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .service-card .btn:hover {\r\n");
      out.write("            background-color: #01aebc;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
