/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2024-10-14 05:01:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.transaction;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_002dpayee_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Fund Transfer  | EasyBank: Banking at Your Fingertips\r\n");
      out.write("</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../assets/style.css\">\r\n");
      out.write("	<script src=\"https://kit.fontawesome.com/72fb3712df.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write(" </head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
 
	if (session.getAttribute("name") == null) {
		response.sendRedirect("../login.jsp");
		return;
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!-- Include Header JSP -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"flex\">\r\n");
      out.write("\r\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/acc-dash.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\" flex-col content-wrapper\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<ul class=\"bredcrumb\">\r\n");
      out.write("<li><a href=\"../home/home.jsp\">Home</a></li>\r\n");
      out.write("    <li><i class=\"fa-solid fa-chevron-right\"></i></li>\r\n");
      out.write("    <li><a href=\"fund-transfer.php\">Fund Transfer Services</a></li>\r\n");
      out.write("    <li><i class=\"fa-solid fa-chevron-right\"></i></li>\r\n");
      out.write("    <li><a href=\"add-payee.jsp\">Add Favorite Payee</a></li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"cardG flex-col\">\r\n");
      out.write("            <h2 class=\"text-center\">Add Payee for Fund Transactions</h2>\r\n");
      out.write("            \r\n");
      out.write("            <p>This form enables users to add a new payee to their favorites for quick and easy fund transfers. \r\n");
      out.write("            Users can enter the payee’s details, streamlining future transactions.</p> <br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <h3 class=\"m-10\">Add Favorite Payee Form</h3>\r\n");
      out.write("\r\n");
      out.write("<form action=\"");
      out.print( request.getContextPath() );
      out.write("/AddPayee\" method=\"POST\" onsubmit=\"return validatePayeeAccountNo()\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"flex flex-col\">\r\n");
      out.write("                 \r\n");
      out.write("                    <div class=\"flex flex-row form\">\r\n");
      out.write("                        <div class=\"form-item flex flex-col\">\r\n");
      out.write("                            <label for=\"\"> Beneficiary Account Number <span class=\"required\">*</span></label>\r\n");
      out.write("                            <input type=\"text\" name=\"PayeeAccountNo\" id=\"PayeeAccountNo\" placeholder=\"PayeeAccountNo\" required>\r\n");
      out.write("                              \r\n");
      out.write("                        </div>\r\n");
      out.write("                        \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-item flex flex-col\">\r\n");
      out.write("                            <label for=\"\"> Beneficiary Name<span class=\"required\">*</span></label>\r\n");
      out.write("                            <input type=\"text\" name=\"PayeeName\" placeholder=\"PayeeName\" required>\r\n");
      out.write("                              \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"flex flex-row form\">\r\n");
      out.write("                        <div class=\"form-item flex flex-col\">\r\n");
      out.write("                            <label for=\"\"> Beneficiary Nickname <span class=\"required\">*</span></label>\r\n");
      out.write("                            <input type=\"text\" name=\"PayeeNickname\" placeholder=\"PayeeNickname\" required>\r\n");
      out.write("                             \r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"flex flex-row form\">\r\n");
      out.write("                        <div class=\"form-item flex flex-col\">\r\n");
      out.write("                            <label for=\"\">  Bank Name <span class=\"required\">*</span></label>                            \r\n");
      out.write("                            <select name=\"Bank\" placeholder=\"Bank\" required>\r\n");
      out.write("                              <option value=\"\">Select the Bank</option>\r\n");
      out.write("							  <option value=\"BOC\">Bank of Ceylon (BOC)</option>\r\n");
      out.write("							  <option value=\"PeoplesBank\">People's Bank</option>\r\n");
      out.write("							  <option value=\"CommercialBank\">Commercial Bank of Ceylon</option>\r\n");
      out.write("							  <option value=\"HNB\">Hatton National Bank (HNB)</option>\r\n");
      out.write("							  <option value=\"SampathBank\">Sampath Bank</option>\r\n");
      out.write("							  <option value=\"NSB\">National Savings Bank (NSB)</option>\r\n");
      out.write("							  <option value=\"SeylanBank\">Seylan Bank</option>\r\n");
      out.write("							  <option value=\"NationsTrustBank\">Nations Trust Bank</option>\r\n");
      out.write("							  <option value=\"DFCC\">DFCC Bank</option>\r\n");
      out.write("							  <option value=\"UnionBank\">Union Bank of Colombo</option>\r\n");
      out.write("							  <option value=\"AmanaBank\">Amana Bank</option>\r\n");
      out.write("							  <option value=\"PanAsiaBank\">Pan Asia Bank</option>\r\n");
      out.write("							  <option value=\"CargillsBank\">Cargills Bank</option>\r\n");
      out.write("							  <option value=\"SCB\">Standard Chartered Bank (Sri Lanka)</option>\r\n");
      out.write("							  <option value=\"HSBC\">HSBC (Sri Lanka)</option>\r\n");
      out.write("							</select> \r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form-item flex flex-col\">\r\n");
      out.write("                            <label for=\"\"> Branch<span class=\"required\">*</span></label>\r\n");
      out.write("                            <select name=\"Branch\" placeholder=\"Branch\" required>\r\n");
      out.write("                             <option value=\"\">Select the Branch</option>\r\n");
      out.write("							  <option value=\"ColomboMain\">Colombo Main Branch</option>\r\n");
      out.write("							  <option value=\"Kandy\">Kandy Branch</option>\r\n");
      out.write("							  <option value=\"Nugegoda\">Nugegoda Branch</option>\r\n");
      out.write("							  <option value=\"Negombo\">Negombo Branch</option>\r\n");
      out.write("							  <option value=\"Galle\">Galle Branch</option>\r\n");
      out.write("							  <option value=\"Kurunegala\">Kurunegala Branch</option>\r\n");
      out.write("							  <option value=\"Matara\">Matara Branch</option>\r\n");
      out.write("							  <option value=\"Jaffna\">Jaffna Branch</option>\r\n");
      out.write("							  <option value=\"Batticaloa\">Batticaloa Branch</option>\r\n");
      out.write("							  <option value=\"Ratnapura\">Ratnapura Branch</option>\r\n");
      out.write("							  <option value=\"Maharagama\">Maharagama Branch</option>\r\n");
      out.write("							  <option value=\"Anuradhapura\">Anuradhapura Branch</option>\r\n");
      out.write("							  <option value=\"Badulla\">Badulla Branch</option>\r\n");
      out.write("							  <option value=\"Avissawella\">Avissawella Branch</option>\r\n");
      out.write("							  <option value=\"Panadura\">Panadura Branch</option>\r\n");
      out.write("							  <option value=\"Kalutara\">Kalutara Branch</option>\r\n");
      out.write("							  <option value=\"Chilaw\">Chilaw Branch</option>\r\n");
      out.write("							  <option value=\"Vavuniya\">Vavuniya Branch</option>\r\n");
      out.write("							  <option value=\"Trincomalee\">Trincomalee Branch</option>\r\n");
      out.write("							  <option value=\"Gampaha\">Gampaha Branch</option>\r\n");
      out.write("							</select>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"flex\" style=\"margin-top: 10px\">\r\n");
      out.write("                    <button type=\"submit\" name=\"submit\" class=\"btn btn-primary\" style=\"margin-right: 10px;\">Confirm</button>\r\n");
      out.write("                    <button type=\"reset\" class=\"btn btn-primary\">Reset</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                 </div>\r\n");
      out.write("                \r\n");
      out.write("            </form>\r\n");
      out.write("            \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("    function validatePayeeAccountNo() {\r\n");
      out.write("        const payeeAccountNo = document.getElementById('PayeeAccountNo').value;\r\n");
      out.write("        if (payeeAccountNo.length < 10 || payeeAccountNo.length > 12) {\r\n");
      out.write("            alert('Payee Account Number must be between 10 and 12 characters.');\r\n");
      out.write("            return false; // Prevent form submission\r\n");
      out.write("        }\r\n");
      out.write("        return true; // Allow form submission\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("   <script>\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        const closeButton = document.getElementById('close-message');\r\n");
      out.write("        const successMessage = document.getElementById('success-message');\r\n");
      out.write("\r\n");
      out.write("        if (closeButton && successMessage) {\r\n");
      out.write("            closeButton.addEventListener('click', function() {\r\n");
      out.write("                successMessage.style.opacity = '0'; // Fade out\r\n");
      out.write("                setTimeout(function() {\r\n");
      out.write("                    successMessage.style.display = 'none'; // Hide after fade out\r\n");
      out.write("                }, 500); // Match the timeout with CSS transition duration\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
