/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2024-12-26 15:59:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.transaction;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class fund_002dotp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Fund Transfer | Your Road to Safety and Savings</title>\r\n");
      out.write("      <link rel=\"stylesheet\" href=\"../assets/style.css\">\r\n");
      out.write("    <!--font awesome-->\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/72fb3712df.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
 
	if (session.getAttribute("name") == null) {
		response.sendRedirect("../login.jsp");
		return;
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("   ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"flex\">\r\n");
      out.write("		\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/acc-dash.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\" flex-col content-wrapper\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"bredcrumb\">\r\n");
      out.write("                <li><a href=\"../home/home.jsp\">Home</a></li>\r\n");
      out.write("                <li><i class=\"fa-solid fa-chevron-right\"></i></li>\r\n");
      out.write("                <li><a href=\"fund-transfer.php\">Fund Transfer Services</a></li>\r\n");
      out.write("                <li><i class=\"fa-solid fa-chevron-right\"></i></li>\r\n");
      out.write("                <li><a href=\"one-timefund.php\">One Time Transfer</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"cardG flex-col\">\r\n");
      out.write("                    <h2 class=\"text-center\">One Time Transfe</h2>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <h3 class=\"m-10\">Add Favorite Beneficiary Summary</h3>\r\n");
      out.write("\r\n");
      out.write("                    <ul>\r\n");
      out.write("                            <li>From Account Number:</li>\r\n");
      out.write("                            <li>First Name:</li>\r\n");
      out.write("                            <li>Beneficiary Account Bank:</li>\r\n");
      out.write("                            <li>Beneficiary Branch Name:</li>\r\n");
      out.write("                            <li>Beneficiary Account Number:</li>\r\n");
      out.write("                            <li>Last Name:</li>\r\n");
      out.write("                            <li>Transfer Amount:</li>\r\n");
      out.write("                            <li>Transfer On:</li>\r\n");
      out.write("                            <li>Beneficiary Contact Number:</li>\r\n");
      out.write("                            <li>Beneficiary Email:</li>\r\n");
      out.write("                            <li>Remark:</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\" flex-col content-wrapper\"></div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"container m-10\">\r\n");
      out.write("                        <div  class=\"m-10\">\r\n");
      out.write("                            <h3 class=\"m-10\">Request OTP</h3>\r\n");
      out.write("\r\n");
      out.write("                            <form action=\"one-timefund.php\" method=\"post\">\r\n");
      out.write("                                    <div>\r\n");
      out.write("                                    <div class=\"form-item  flex-col\"> \r\n");
      out.write("                                <label class=\"m-10\">Delivery Method:</label> <br>\r\n");
      out.write("\r\n");
      out.write("                                <input class=\"m-10\" type=\"radio\" id=\"sms\" name=\"deliveryMethod\" value=\"SMS\" checked>\r\n");
      out.write("                                <label class=\"m-10\"  for=\"sms\">SMS</label>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                <input type=\"radio\" id=\"email\" name=\"deliveryMethod\" value=\"EMAIL\">\r\n");
      out.write("                                <label for=\"email\">EMAIL</label>\r\n");
      out.write("\r\n");
      out.write("                                <button type=\"reset\" class=\"btn btn-primary\" style=\"margin-left: 150px; width:200px\">Request OTP</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                          \r\n");
      out.write("\r\n");
      out.write("                                <div class=\"flex flex-row form\">\r\n");
      out.write("                                <div class=\"form-item flex flex-col\">\r\n");
      out.write("                                    <label for=\"\">OTP <span class=\"required\">*</span></label>\r\n");
      out.write("                                    <input type=\"text\" name=\"otp\" placeholder=\"OTP\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                    \r\n");
      out.write("                                    <div>\r\n");
      out.write("                                <div class=\"form-item flex flex-col\">\r\n");
      out.write("                               \r\n");
      out.write("                                <a href=\"success-transfer.jsp\"> \r\n");
      out.write("                                    <button type=\"reset\" class=\"btn btn-primary\" style=\"margin-right: 15px; width:100px\" > \r\n");
      out.write("                                    <a href=\"success-transfer.jsp\"> Confirm   </a></button>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
