/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.96
 * Generated at: 2024-10-13 19:25:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.transaction;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import config.dbconnect;
import javax.servlet.http.HttpSession;

public final class payee_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("javax.servlet.http.HttpSession");
    _jspx_imports_classes.add("config.dbconnect");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!-- Import the dbconnect class -->\r\n");
      out.write(" \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Fund Transfer | EasyBank: Banking at Your Fingertips\r\n");
      out.write("</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../assets/style.css\">\r\n");
      out.write("    <!-- Font Awesome -->\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/72fb3712df.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
 
	if (session.getAttribute("name") == null) {
		response.sendRedirect("../login.jsp");
		return;
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Include Header JSP -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"flex\">\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../inc/acc-dash.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"flex-col content-wrapper\">\r\n");
      out.write("            <ul class=\"bredcrumb\">\r\n");
      out.write("                <li><a href=\"../home/home.jsp\">Home</a></li>\r\n");
      out.write("                <li><i class=\"fa-solid fa-chevron-right\"></i></li>\r\n");
      out.write("                <li><a href=\"../transaction/index.jsp\">Fund Transfer Services</a></li>\r\n");
      out.write("                <li><i class=\"fa-solid fa-chevron-right\"></i></li>\r\n");
      out.write("                <li>Favorite Payee</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"cardG flex-col\">\r\n");
      out.write("                    <h2 class=\"text-center\">Favorite Payee</h2>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Success Message Section -->\r\n");
      out.write("                    ");
 
                    String successMessage = (String) session.getAttribute("success_message");
                    if (successMessage != null) {
                    
      out.write("\r\n");
      out.write("                        <div class=\"alert fade-in\" id=\"successMessage\">\r\n");
      out.write("                            ");
      out.print( successMessage );
      out.write("\r\n");
      out.write("                            <button class=\"btn-close\" onclick=\"this.parentElement.style.display='none';\">&times;</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    ");

                        // Remove the message after displaying it
                        session.removeAttribute("success_message");
                    }
                    
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <script>\r\n");
      out.write("                        // Set a timeout to hide the success message after 5 seconds\r\n");
      out.write("                        setTimeout(function() {\r\n");
      out.write("                            var successMessage = document.getElementById('successMessage');\r\n");
      out.write("                            if (successMessage) {\r\n");
      out.write("                                successMessage.style.opacity = '0'; // Fade out\r\n");
      out.write("                                setTimeout(function() {\r\n");
      out.write("                                    successMessage.style.display = 'none'; // Remove from the DOM\r\n");
      out.write("                                }, 500); // Wait for fade-out transition\r\n");
      out.write("                            }\r\n");
      out.write("                        }, 5000);\r\n");
      out.write("                    </script>\r\n");
      out.write("\r\n");
      out.write("                    <!-- Search bar and + button -->\r\n");
      out.write("                    <div class=\"search-container\">\r\n");
      out.write("                        <a href=\"add-payee.jsp\">\r\n");
      out.write("                            <button class=\"btn btn-primary align-center flex\">+ Add Favorite Payee</button>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <h4 class=\"m-10\">Favourite Payee</h4>\r\n");
      out.write("\r\n");
      out.write("                    <table>\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>Beneficiary Nickname</th>\r\n");
      out.write("                                <th>Beneficiary Account Number</th>\r\n");
      out.write("                                <th>Bank</th>\r\n");
      out.write("                                <th>Branch</th>\r\n");
      out.write("                                <th>Action(s)</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            ");
 
                            String NIC = (String) session.getAttribute("NIC");
                            String sql = "SELECT PayeeId, PayeeAccountNo, PayeeName, PayeeNickname, Bank, Branch FROM payees WHERE NIC = ?";
                            try (Connection conn = dbconnect.connect();
                                 PreparedStatement stmt = conn.prepareStatement(sql)) {

                                stmt.setString(1, NIC);
                                ResultSet rs = stmt.executeQuery();

                                while (rs.next()) {
                                	String payeeName = rs.getString("PayeeName");
                                    String payeeAccountNo = rs.getString("PayeeAccountNo");
                                    String payeeNickname = rs.getString("PayeeNickname");
                                    String payeeId = rs.getString("PayeeId");
                                    String bank = rs.getString("Bank");
                                    String branch = rs.getString("Branch"); 
                            
      out.write("\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>");
      out.print( payeeNickname );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( payeeAccountNo );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( bank );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( branch );
      out.write("</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <div style=\"display: flex; gap: 10px; padding: 10px; padding-bottom: 10px; padding-left: 30px;\">\r\n");
      out.write("                                            <a href=\"editPayee.jsp?payeeId=");
      out.print( payeeId );
      out.write("\">\r\n");
      out.write("                                                <button class=\"btn btn-primary\" style=\"width:100px;\">Edit</button>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <a href=\"javascript:void(0);\" class=\"delete-button\" data-id=\"");
      out.print( payeeId );
      out.write("\">\r\n");
      out.write("                                                <button class=\"btn btn-danger\" style=\"width:100px;\">Delete</button>\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                      </div>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            ");
 
                                }
                            } catch (SQLException e) {
                                e.printStackTrace();
                            } 
                            
      out.write("\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <script>\r\n");
      out.write("        var deleteButtons = document.querySelectorAll('.delete-button');\r\n");
      out.write("\r\n");
      out.write("        deleteButtons.forEach(function(button) {\r\n");
      out.write("            button.addEventListener('click', function() {\r\n");
      out.write("                var id = this.getAttribute('data-id');\r\n");
      out.write("                Swal.fire({\r\n");
      out.write("                    title: 'Are you sure?',\r\n");
      out.write("                    text: \"You won't be able to revert this!\",\r\n");
      out.write("                    icon: 'warning',\r\n");
      out.write("                    showCancelButton: true,\r\n");
      out.write("                    confirmButtonColor: '#3085d6',\r\n");
      out.write("                    cancelButtonColor: '#d33',\r\n");
      out.write("                    confirmButtonText: 'Yes, delete it!'\r\n");
      out.write("                }).then((result) => {\r\n");
      out.write("                    if (result.isConfirmed) {\r\n");
      out.write("                        window.location.href = '");
      out.print( request.getContextPath() );
      out.write("/DeletePayee?id=' + id;\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("    document.addEventListener('DOMContentLoaded', function() {\r\n");
      out.write("        const closeButton = document.getElementById('close-message');\r\n");
      out.write("        const successMessage = document.getElementById('success-message');\r\n");
      out.write("\r\n");
      out.write("        if (closeButton && successMessage) {\r\n");
      out.write("            closeButton.addEventListener('click', function() {\r\n");
      out.write("                successMessage.style.opacity = '0'; // Fade out\r\n");
      out.write("                setTimeout(function() {\r\n");
      out.write("                    successMessage.style.display = 'none'; // Hide after fade out\r\n");
      out.write("                }, 500); // Match the timeout with CSS transition duration\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
